#!/bin/bash
# FOR as time as you can read this text it means this file is in raw mode. so don't try to use it..

yum -y update
yum -y install git wget zip unzip epel-release nano curl
yum install pygpgme yum-utils

# ===================================================================================
sed -i 's/^apache_port=.*/apache_port=127.0.0.1:7171/' /var/cpanel/cpanel.config
sed -i 's/^apache_ssl_port=.*/apache_ssl_port=127.0.0.1:7443/' /var/cpanel/cpanel.config
/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings
# ===================================================================================

# ===================================================================================
# ===================================================================================
curl -s https://packagecloud.io/install/repositories/varnishcache/varnish52/script.rpm.sh | sudo bash
yum -y install varnish varnish-devel
service varnish stop
cd /etc/varnish/; rm -Rf default.vcl; rm -Rf varnish.params
wget https://raw.githubusercontent.com/DopeCloud/nginx-varnish-cpanel/master/etc/varnish/varnish.params
wget https://raw.githubusercontent.com/DopeCloud/nginx-varnish-cpanel/master/etc/varnish/default.vcl
service varnish start
# ===================================================================================
# ===================================================================================

# ===================================================================================
# Nginx
# ===================================================================================
mkdir -p /opt/nginx/sources
mkdir -p /opt/nginx/mods
mkdir -p /opt/nginx/libs
chown -R root:root /opt/nginx/sources
chown -R root:root /opt/nginx/mods
chown -R root:root /opt/nginx/libs
yum check-update || sudo yum update -y
yum groupinstall -y 'Development Tools'
yum install -y perl perl-devel perl-ExtUtils-Embed libxslt libxslt-devel libxml2 libxml2-devel gd gd-devel GeoIP GeoIP-devel
yum install zlib zlib-devel -y

cd /opt/nginx/sources; wget 'https://nginx.org/download/nginx-1.9.9.tar.gz'
tar xf nginx-1.9.9.tar.gz; rm -Rf nginx-1.9.9.tar.gz; mv nginx-1.9.9/ nginx; chown -R root:root nginx/
# ===================================================================================
# ===================================================================================

# ===================================================================================
# ===================================================================================
cd /opt/nginx/libs/; wget 'https://www.openssl.org/source/openssl-1.1.0g.tar.gz'
tar xf openssl-1.1.0g.tar.gz; rm -Rf openssl-1.1.0g.tar.gz; mv openssl-1.1.0g/ openssl

cd /opt/nginx/libs/; wget 'https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz'
tar xf pcre-8.41.tar.gz; rm -Rf pcre-8.41.tar.gz; mv pcre* pcre

cd /opt/nginx/libs/; wget 'https://www.zlib.net/zlib-1.2.11.tar.gz'
tar xf zlib-1.2.11.tar.gz; rm -Rf zlib-1.2.11.tar.gz; mv zlib* zlib
# ===================================================================================
# ===================================================================================

# ===================================================================================
# ===================================================================================
# LuaJIT Library
cd /opt/nginx/modules/
git clone http://luajit.org/git/luajit-2.0.git
cd luajit-2.0/
make -j`nproc`
sudo make install
ldconfig
# ===================================================================================
yum -y install gcc-c++ flex bison yajl yajl-devel curl-devel curl GeoIP-devel doxygen zlib-devel
cd /opt/nginx/libs/; git clone https://github.com/SpiderLabs/ModSecurity
cd /opt/nginx/libs/ModSecurity/
git checkout -b v3/master origin/v3/master
sh build.sh
git submodule init
git submodule update
./configure
make -j`nproc`
make install
ldconfig
# ===================================================================================


# ===================================================================================
cd /opt/nginx/mods/
git clone https://github.com/ildus/nginx_redis.git
cd /opt/nginx/mods/nginx_redis/
mv ngx_devel_kit-0.*/ /opt/nginx/mods/ngx_devel_kit
cd /opt/nginx/mods/; rm -Rf /opt/nginx/mods/nginx_redis


cd /opt/nginx/mods/; git clone https://github.com/openresty/set-misc-nginx-module.git
cd /opt/nginx/mods/; git clone https://github.com/openresty/encrypted-session-nginx-module.git
cd /opt/nginx/mods/; git clone https://github.com/Qihoo360/ngx_http_subrange_module.git
cd /opt/nginx/mods/; git clone https://github.com/SpiderLabs/ModSecurity-nginx.git
cd /opt/nginx/mods/; git clone https://github.com/vozlt/nginx-module-vts.git
cd /opt/nginx/mods/; git clone https://github.com/FRiCKLE/ngx_cache_purge.git
cd /opt/nginx/mods/; git clone https://github.com/kyprizel/testcookie-nginx-module.git
cd /opt/nginx/mods/; git clone https://github.com/openresty/headers-more-nginx-module.git
cd /opt/nginx/mods/; git clone https://github.com/openresty/echo-nginx-module.git
cd /opt/nginx/mods/; git clone https://github.com/arut/nginx-dav-ext-module.git
cd /opt/nginx/mods/; git clone https://github.com/masterzen/nginx-upload-progress-module.git
cd /opt/nginx/mods/; git clone https://github.com/nginx-clojure/nginx-access-plus.git
cd /opt/nginx/mods/; git clone https://github.com/leev/ngx_http_geoip2_module.git
cd /opt/nginx/mods/; git clone https://github.com/flant/nginx-http-rdns.git
cd /opt/nginx/mods/; git clone https://github.com/openresty/lua-nginx-module.git
# ===================================================================================
cd /opt/nginx/sources/nginx/
export MODSECURITY_INC="/opt/nginx/libs/ModSecurity/headers/"
export MODSECURITY_LIB="/opt/nginx/libs/ModSecurity/src/.libs/"
./configure \
--user=nginx \
--group=nginx \
--sbin-path=/usr/sbin/nginx           \
--conf-path=/nginx/nginx.conf     \
--pid-path=/var/run/nginx.pid         \
--lock-path=/var/run/nginx.lock       \
--error-log-path=/nginx/logs/error.log \
--http-log-path=/nginx/logs/access.log \
--with-pcre                           \
--with-http_geoip_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_image_filter_module \
--with-http_secure_link_module \
--with-http_sub_module \
--with-http_xslt_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_realip_module \
--with-stream \
--with-stream_ssl_module \
--with-threads \
--with-http_dav_module \
--with-ld-opt="-Wl,-rpath,/usr/local/lib/" \
--add-module=/opt/nginx/mods/ngx_devel_kit \
--add-module=/opt/nginx/mods/testcookie-nginx-module \
--add-module=/opt/nginx/mods/set-misc-nginx-module \
--add-module=/opt/nginx/mods/headers-more-nginx-module \
--add-module=/opt/nginx/mods/echo-nginx-module \
--add-module=/opt/nginx/mods/nginx-access-plus/src/c \
--add-module=/opt/nginx/mods/nginx-dav-ext-module \
--add-module=/opt/nginx/mods/nginx-module-vts \
--add-module=/opt/nginx/mods/ngx_cache_purge \
--add-module=/opt/nginx/mods/ngx_http_geoip2_module \
--add-module=/opt/nginx/mods/nginx-http-rdns \
--add-module=/opt/nginx/mods/lua-nginx-module \
--add-module=/opt/nginx/mods/ModSecurity-nginx \
--add-module=/opt/nginx/mods/encrypted-session-nginx-module \
--add-module=/opt/nginx/mods/ngx_http_subrange_module \
--add-module=/opt/nginx/mods/nginx-upload-progress-module
make -j`nproc`
make install

sudo useradd --system --home /var/cache/nginx --shell /sbin/nologin --comment "nginx user" --user-group nginx
mkdir -p /nginx/live
mkdir -p /nginx/logs
mkdir -p /nginx/cache
mkdir -p /nginx/conf.d
touch /nginx/logs/access.log
touch /nginx/logs/error.log
cd /usr/lib/systemd/system/; wget https://raw.githubusercontent.com/DopeCloud/nginx-varnish-cpanel/master/nginx/static/nginx.service
systemctl enable nginx.service
cd /nginx/; rm -Rf *.default
rm -Rf nginx.conf; wget https://raw.githubusercontent.com/DopeCloud/nginx-varnish-cpanel/master/nginx/nginx.conf
service nginx start
