#!/bin/bash
# FOR as time as you can read this text it means this file is in raw mode. so don't try to use it..

yum -y update
yum -y install git wget zip unzip epel-release nano curl
yum install pygpgme yum-utils
curl -s https://packagecloud.io/install/repositories/varnishcache/varnish52/script.rpm.sh | sudo bash
